# Generated by Django 5.2 on 2025-04-09 19:00

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorDataAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('p1', models.FloatField()),
                ('p2', models.FloatField()),
                ('signal', models.IntegerField()),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'db_table': 'sensor_data_air',
            },
        ),
        migrations.CreateModel(
            name='SensorDataIndoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('aqi', models.IntegerField()),
                ('tvoc', models.IntegerField()),
                ('eco2', models.IntegerField()),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'db_table': 'sensor_data_indoor',
            },
        ),
        migrations.CreateModel(
            name='SensorDataTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'db_table': 'sensor_data_temp',
            },
        ),
    ]
