apiVersion: v1
kind: ConfigMap
metadata:
  name: sensors-config
  namespace: sensors
data:
  DEBUG: "True"
  APP_PORT: "4040"           # must match containerPort in deployment.yaml
  DB_HOST: "192.168.33.5"   # Your existing TimescaleDB host
  DB_PORT: "5432"
  DB_NAME: "sensors"
  DB_USER: "postgres"
  TZ: "Europe/Athens"
  REDIS_HOST: "192.168.33.5"   # Shared Redis on UNRAID
  REDIS_PORT: "6379"
  REDIS_DB: "1"                # db 0 is used by another app
