apiVersion: v1
kind: ConfigMap
metadata:
  name: sensors-config
  namespace: sensors
data:
  DEBUG: "True"
  DB_HOST: "192.168.33.5"   # Your existing TimescaleDB host
  DB_PORT: "5432"
  DB_NAME: "sensors"
  DB_USER: "postgres"
  TZ: "Europe/Athens"
  REDIS_HOST: "192.168.33.5"
